### ISSUE TITLE
Datasheet?

### ISSUE THREAD

**Issue by Sofus199** [GuidodiPasquo/Arduino_Quaternion_for_rockets#2]
Can you link the data sheet you used, can't find any matching what you refer to in code. By the way, it works and I love it!!!!!!

**Comment by GuidodiPasquo** [comment]
Of course, I tested the code on an MPU6050 and took the quaternion math from wikipedia. 
https://invensense.tdk.com/wp-content/uploads/2015/02/MPU-6000-Datasheet1.pdf
https://en.wikipedia.org/wiki/Quaternion
https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation

**Comment by Sofus199** [comment]
Thanks! I'll close it now.
